name: oguz_taxi_v2_v2
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_osm_plugin: any         
  pointer_interceptor: ^0.9.3+3
  flutter_hooks: ^0.18.5+1
  
  geolocator: ^9.0.2
  open_route_service: ^1.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: 
  otp_text_field: ^1.1.3
  connectivity_plus: ^3.0.3
  flutter_spinkit: ^5.1.0
  web_socket_channel: ^2.4.0
  osm_flutter_hooks: ^1.3.0

dev_dependencies:
  build_runner: ^2.2.0
  hive_generator: ^2.0.1

  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
     - assets/
     - assets/images/
     - assets/icon/
     - assets/icon/ic_map.png
     - assets/icon/close.png
     - assets/images/taxi.png